/**
 * Brand identity facts that more than one file has to agree on.
 *
 * Distinct from `SENDER_IDENTITY` in ./consent.ts, which is the legal sender
 * block CASL requires on commercial email and is versioned against what
 * subscribers were shown. This is the public-facing brand: what the site
 * links to, and what its structured data claims to be.
 */

/**
 * Every profile the brand controls elsewhere, as absolute URLs.
 *
 * Feeds two things that must not drift: the nav drawer's outbound links
 * (Base.astro) and schema.org `sameAs`, which is how an entity on this domain
 * gets reconciled with the same entity on another one. A profile listed here
 * and not actually owned is a bad claim, so add only what the brand controls.
 */
export const SOCIAL_PROFILES = {
  instagram: 'https://instagram.com/nuageathletics',
} as const

/**
 * Stable @id for the Organization node.
 *
 * JSON-LD nodes are only "the same thing" if they share an @id, so the
 * Organization that `Seo.astro` emits on every page and the `brand` that
 * `ProductView.astro` hangs off the Product have to name the identical
 * string. A fragment on the site origin is the convention, and it stays
 * stable across every page because the origin does.
 */
export function organizationId(site: string): string {
  return `${site}/#organization`
}

/** Stable @id for the WebSite node, same reasoning as above. */
export function websiteId(site: string): string {
  return `${site}/#website`
}

/**
 * The link-preview card. Regenerated by scripts/og-image.mjs — see that file
 * for why this is a flattened JPEG rather than one of the product webps.
 */
export const OG_IMAGE = {
  path: '/img/og-default.jpg',
  type: 'image/jpeg',
  width: 1200,
  height: 630,
} as const
