/**
 * Print counterpart to shopify/src/shell.ts — the branded frame around the
 * packing slip, the one piece of this brand that arrives on paper.
 *
 * Everything the email shell does to survive a mail client is *absent* here,
 * on purpose, and it is worth saying which and why, because the two files
 * otherwise look like they should be one:
 *
 *  - **A `<style>` block, not inlined declarations.** The email shell inlines
 *    every colour because Outlook's Word engine drops `var()` and Gmail's
 *    sanitiser strips unrecognised declarations. Shopify renders a packing
 *    slip in the admin and prints it from the browser, so there is a real
 *    CSS engine here — and `@page` (the sheet's own margin) and
 *    `page-break-inside` cannot be expressed inline at all. A slip that
 *    splits a line item across two sheets is the failure this buys off.
 *  - **No table-based layout, no MSO conditional, no `[data-ogsc]`
 *    auto-invert defense.** There is no Outlook here and nothing inverts a
 *    sheet of paper.
 *  - **No sky backdrop and no painted ground.** See PRINT_THEME's doc
 *    comment: the ground is the sheet, and painting it costs toner on every
 *    order and prints as a grey box on plain paper.
 *  - **No unsubscribe, ever.** Not a CASL judgement call the way the email
 *    shell's `includeUnsubscribe` is — paper has no unsubscribe. The
 *    generator's lint rejects the string outright rather than making it a
 *    per-template flag.
 *
 * What *is* shared with the email side is the part that would actually drift:
 * `t()` and `LOCALE_PRELUDE` from ../liquid.ts (so a bilingual string is
 * built the same way and a locale resolves the same way, French-first), and
 * `SENDER_IDENTITY` from src/lib/consent.ts. The palette is deliberately not
 * shared — see PRINT_THEME.
 */
import { SENDER_IDENTITY } from '../../../src/lib/consent.ts'
import { LOCALE_PRELUDE, t, isoDate } from '../liquid.ts'
import {
  PRINT_THEME,
  PRINT_WORDMARK_PATH,
  PRINT_WORDMARK_WIDTH,
  PRINT_WORDMARK_HEIGHT,
} from './theme.ts'

/** Same production domain shopify/src/shell.ts uses, and for the same
 * reason: Shopify's own `shop.url` points at whichever channel is primary —
 * today the dead Online Store channel (CLAUDE.md, #88/#90) — so no asset URL
 * is ever built off it. A packing slip rendered inside the Shopify admin has
 * no origin of ours to be relative to either. */
export const SITE_URL = 'https://nuageathletics.com'

export interface PrintShellArgs {
  /** Liquid/HTML for the <title> and the document's own heading. Build with t(). */
  heading: string
  /** Liquid/HTML for the document body. */
  bodyLiquid: string
}

export function renderPrintShell({ heading, bodyLiquid }: PrintShellArgs): string {
  const p = PRINT_THEME
  const wordmarkUrl = `${SITE_URL}${PRINT_WORDMARK_PATH}`
  const htmlLang = t('fr-CA', 'en-CA')

  return `{% comment %}
  Generated by shopify/src/print — do not hand-edit. See shopify/print/README.md.
{% endcomment %}
${LOCALE_PRELUDE}
<!doctype html>
<html lang="${htmlLang}">
  <head>
    <meta charset="utf-8" />
    <title>${heading}</title>
    <style>
      /* The sheet's own margin. A packing slip is read once, next to the
         garment it describes — generous margins cost nothing and keep the
         fold off the type. */
      @page { margin: 14mm; }

      body {
        margin: 0;
        font-family: ${p.fontSans};
        font-size: 12pt;
        line-height: 1.5;
        color: ${p.ink};
        /* No background declaration: the ground is the sheet. */
      }

      /* Points, not pixels, throughout: this document has exactly one
         medium and it is measured in physical units. */
      .na-wordmark { display: block; width: ${PRINT_WORDMARK_WIDTH}px; height: auto; border: 0; }
      .na-head { display: flex; justify-content: space-between; align-items: flex-start; gap: 16pt; margin: 0 0 24pt; }
      .na-title { font-family: ${p.fontDisplay}; font-size: 13pt; font-weight: 600; letter-spacing: ${p.trackingLabel}; text-transform: uppercase; margin: 0 0 4pt; }
      .na-meta { text-align: right; font-size: 10pt; line-height: 1.6; color: ${p.mute}; white-space: nowrap; }
      .na-meta strong { color: ${p.ink}; font-weight: 600; }

      .na-cols { display: flex; gap: 24pt; margin: 0 0 24pt; }
      .na-col { flex: 1; font-size: 10pt; line-height: 1.6; }
      .na-label { font-size: 9pt; letter-spacing: ${p.trackingLabel}; text-transform: uppercase; color: ${p.mute}; margin: 0 0 4pt; }

      table { width: 100%; border-collapse: collapse; margin: 0 0 20pt; }
      th { font-size: 9pt; letter-spacing: ${p.trackingLabel}; text-transform: uppercase; color: ${p.mute}; font-weight: 600; text-align: left; padding: 0 0 6pt; border-bottom: 1px solid ${p.ink}; }
      th.na-qty, td.na-qty { text-align: right; white-space: nowrap; width: 1%; padding-left: 12pt; }
      td { font-size: 11pt; padding: 8pt 0; border-bottom: 1px solid ${p.line}; vertical-align: top; }
      /* A line item split across two sheets is the one layout failure that
         actually matters when someone is picking an order from a printout. */
      tr { page-break-inside: avoid; }
      .na-variant { display: block; font-size: 9.5pt; color: ${p.mute}; }
      .na-sku { display: block; font-size: 9pt; color: ${p.mute}; letter-spacing: 0.04em; }

      .na-note { border: 1px solid ${p.line}; padding: 10pt 12pt; margin: 0 0 20pt; font-size: 10pt; }
      .na-msg { font-size: 10.5pt; line-height: 1.6; margin: 0 0 6pt; }
      .na-foot { margin: 28pt 0 0; padding: 10pt 0 0; border-top: 1px solid ${p.line}; font-size: 9pt; line-height: 1.6; color: ${p.mute}; }
    </style>
  </head>
  <body>
    <div class="na-head">
      <div>
        <img src="${wordmarkUrl}" width="${PRINT_WORDMARK_WIDTH}" height="${PRINT_WORDMARK_HEIGHT}" alt="${SENDER_IDENTITY.name}" class="na-wordmark" />
      </div>
      <div class="na-meta">
        <div class="na-title">${heading}</div>
        <div><strong>{{ order.name }}</strong></div>
        <div>${isoDate('order.created_at')}</div>
      </div>
    </div>
${bodyLiquid}
    <div class="na-foot">
      ${SENDER_IDENTITY.name}<br />
      {{ shop.address.summary }}<br />
      ${SENDER_IDENTITY.email}
    </div>
  </body>
</html>`
}
