/**
 * Shopify-notification counterpart to src/lib/email.ts's `renderEmailShell`.
 * Every visual decision below is copied from that function rather than
 * reinvented, because CLAUDE.md's whole point for this issue is that a
 * Shopify order email must not look like a different company than the
 * Resend-sent mail a subscriber already got. Read renderEmailShell's doc
 * comments for *why* each Outlook/Gmail workaround exists (table layout, the
 * `background=` attribute, the always-dark palette instead of a
 * light/dark toggle, the `[data-ogsc]`/`[data-ogsb]` override on the one CTA
 * button) — they apply identically here and aren't repeated line by line.
 *
 * Three differences from the Resend shell, all because Shopify notifications
 * aren't rendered by this codebase:
 *  - Locale is resolved at Shopify's send time by `LOCALE_PRELUDE`
 *    (liquid.ts), not passed in as an argument.
 *  - The mailing address is Shopify's own `shop.address`, not the
 *    `SENDER_ADDRESS` secret — see shopify/notifications/README.md for why,
 *    and CLAUDE.md non-negotiable/ADR-0007 for why no address is committed
 *    to source at all.
 *  - There's no `<img>` at a relative `/img/...` path to resolve against a
 *    request origin; every asset URL is absolute against the production
 *    domain (`SITE_URL` below), because a Shopify-rendered email has no
 *    origin of its own to be relative to.
 */
import { EMAIL_THEME, WORDMARK_PATH, SKY_BG_PATH, OUTER_BG } from '../../src/lib/email.ts'
import { SENDER_IDENTITY } from '../../src/lib/consent.ts'
import { LOCALE_PRELUDE, t } from './liquid.ts'

/** Same production domain src/lib/email.ts's callers pass as `siteUrl`
 * (wrangler.toml's PUBLIC_SITE_URL / astro.config.mjs's `site`). Shopify's
 * own `shop.url` points at whichever channel is primary — today the dead
 * Online Store channel (CLAUDE.md, #88/#90) — so assets are never built off
 * it. */
export const SITE_URL = 'https://nuageathletics.com'

const WORDMARK_WIDTH = 120
const WORDMARK_HEIGHT = 29

export interface ShellArgs {
  /** Liquid/HTML for the <title> and the big heading. Build with t(). */
  heading: string
  /** Liquid/HTML preheader text (the hidden preview-pane snippet). */
  preheader: string
  /** Liquid/HTML for the message body — already-built blocks.ts output. */
  bodyLiquid: string
  /** True only for the abandoned-checkout template — a marketing message
   * under CASL, which is the one notification in scope here that needs an
   * unsubscribe path. Every other template is transactional order mail and
   * carries none, same rule as renderEmailShell's optional `unsubUrl`. */
  includeUnsubscribe?: boolean
}

/**
 * Renders the full <html> document. The locale prelude is emitted first so
 * every later `{% if en %}` in heading/body/footer has `en` defined.
 */
export function renderShell({ heading, preheader, bodyLiquid, includeUnsubscribe }: ShellArgs): string {
  const t_ = EMAIL_THEME
  const wordmarkUrl = `${SITE_URL}${WORDMARK_PATH}`
  const skyUrl = `${SITE_URL}${SKY_BG_PATH}`
  const htmlLang = t('fr-CA', 'en-CA')
  const brandAlt = SENDER_IDENTITY.name

  const contactLine = t(
    `Une question sur votre commande&nbsp;? Écrivez-nous à <a href="mailto:${SENDER_IDENTITY.email}" style="color:${t_.accentInk};">${SENDER_IDENTITY.email}</a>.`,
    `A question about your order? Write to us at <a href="mailto:${SENDER_IDENTITY.email}" style="color:${t_.accentInk};">${SENDER_IDENTITY.email}</a>.`
  )

  const unsubscribeLine = includeUnsubscribe
    ? `{% if unsubscribe_url %}<br /><a href="{{ unsubscribe_url }}" style="color:${t_.mute};">${t('Se désabonner', 'Unsubscribe')}</a>{% endif %}`
    : ''

  return `{% comment %}
  Generated by shopify/src — do not hand-edit. See shopify/notifications/README.md.
{% endcomment %}
${LOCALE_PRELUDE}
<!doctype html>
<html lang="${htmlLang}" style="color-scheme: light dark;">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="color-scheme" content="light dark" />
    <meta name="supported-color-schemes" content="light dark" />
    <!--[if mso]>
    <noscript>
      <xml>
        <o:OfficeDocumentSettings>
          <o:PixelsPerInch>96</o:PixelsPerInch>
        </o:OfficeDocumentSettings>
      </xml>
    </noscript>
    <![endif]-->
    <title>${heading}</title>
    <style>
      [data-ogsc] .email-btn, [data-ogsb] .email-btn {
        background-color: ${t_.ink} !important;
        color: ${t_.paper} !important;
      }
    </style>
  </head>
  <body style="margin:0;padding:0;background-color:${OUTER_BG};">
    <div style="display:none;max-height:0;overflow:hidden;opacity:0;">${preheader}</div>
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="${OUTER_BG}" background="${skyUrl}" style="background-color:${OUTER_BG};background-image:url('${skyUrl}');background-repeat:no-repeat;background-position:center top;background-size:cover;">
      <tr>
        <td align="center" style="padding:48px 16px;">
          <!--[if mso]>
          <table role="presentation" width="520" cellpadding="0" cellspacing="0" border="0"><tr><td>
          <![endif]-->
          <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="${t_.paper}" style="max-width:520px;background-color:${t_.paper};border:1px solid ${t_.line};">
            <tr>
              <td align="center" style="padding:40px 32px;font-family:${t_.fontSans};color:${t_.ink};text-align:center;">
                <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
                  <tr>
                    <td align="center" style="padding:0 0 28px;text-align:center;">
                      <img
                        src="${wordmarkUrl}"
                        width="${WORDMARK_WIDTH}"
                        height="${WORDMARK_HEIGHT}"
                        alt="${brandAlt}"
                        style="display:block;margin:0 auto;border:0;outline:none;width:${WORDMARK_WIDTH}px;height:auto;"
                      />
                    </td>
                  </tr>
                  <tr>
                    <td align="center" style="padding:0 0 16px;font-family:${t_.fontDisplay};font-size:22px;font-weight:600;line-height:1.3;text-align:center;">
                      ${heading}
                    </td>
                  </tr>
                  <tr>
                    <td align="left" style="text-align:left;">
                      ${bodyLiquid}
                    </td>
                  </tr>
                  <tr>
                    <td align="center" style="padding:8px 0 0;font-size:13px;color:${t_.mute};line-height:1.6;text-align:center;">
                      ${contactLine}
                    </td>
                  </tr>
                  <tr>
                    <td style="padding:32px 0 16px;">
                      <div style="border-top:1px solid ${t_.line};line-height:0;font-size:0;">&nbsp;</div>
                    </td>
                  </tr>
                  <!-- No CASL sender block: this shell serves Shopify's own
                       customer-notification mail, not the CASL-commercial
                       mail src/lib/email.ts sends (see #91's scope note).
                       The name/address/email footer below is Shopify's own
                       required identification for order mail, not a CASL
                       substitute — SENDER_IDENTITY.name and .email are
                       hardcoded from src/lib/consent.ts; the address is
                       shop.address, resolved by whatever Settings → Store
                       details holds (see #93 and this directory's README). -->
                  <tr>
                    <td align="center" style="font-size:12px;color:${t_.mute};line-height:1.6;text-align:center;">
                      ${SENDER_IDENTITY.name}<br />
                      {{ shop.address.summary }}<br />
                      <a href="mailto:${SENDER_IDENTITY.email}" style="color:${t_.mute};">${SENDER_IDENTITY.email}</a>${unsubscribeLine}
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
          </table>
          <!--[if mso]>
          </td></tr></table>
          <![endif]-->
        </td>
      </tr>
    </table>
  </body>
</html>`
}
